services:

  auth-server:
    build:
      context: auth_server
    container_name: auth-server
    ports:
      - "9000:9000"
      - "5006:5006"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"

  resource-db:
    image: postgres:16
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_server_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - resource_data:/var/lib/postgresql/data

  resource-server:
    build:
      context: resource_server
    container_name: resource-server
    ports:
      - "8080:8080"
      - "5007:5007"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://resource-db:5432/resource_server_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    depends_on:
      - resource-db

volumes:
  resource_data:
